---
<div style="text-align: center; font-family: 'Times New Roman', Times, serif;">
  <h1>Python</h1>
 <h1>Numpy</h1>
 <div> Note Book Author: Shahzaib Yaqoob<div>
 <div> Gmail :shahzaibmalik4488gmail.com<hdiv5> 
 
 ---
</div>


In [90]:
import numpy as np

In [91]:
Array_data=np.array([1,2,3,4,5,6])

In [92]:
Array_data

array([1, 2, 3, 4, 5, 6])

<div style="font-family: 'Times New Roman', Times, serif;">
  <h3 style="text-align: center;">Types of Array</h3>
  <div style="margin-left: 4mm;">- 1D (One Dimensional Array)</div>
  <div style="margin-left: 4mm;">- 2D (Two Dimensional Array)</div>
  <div style="margin-left: 4mm;">- 3D (Three Dimensional)</div>


In [93]:
# 1D Array
Data_Array1=np.array([1,2,3,4,5,6])
Data_Array1

array([1, 2, 3, 4, 5, 6])

In [94]:
# 2D Array
data_Array2=np.array([[1,2,3,4,],[5,6,7,8]]) # create Array 2 X 2
data_Array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
# 3D Array
data_Array3 = np.array([[[1, 2, 3.4], [1, 2, 3.4], [1, 2, 3.4]],[[4, 5, 6.7], [4, 5, 6.7], [4, 5, 6.7]]])
data_Array3

array([[[1. , 2. , 3.4],
        [1. , 2. , 3.4],
        [1. , 2. , 3.4]],

       [[4. , 5. , 6.7],
        [4. , 5. , 6.7],
        [4. , 5. , 6.7]]])