---
<div style="text-align: center; font-family: 'Times New Roman', Times, serif;">
  <h1>Python</h1>
 <h1>Numpy</h1>
 <div> Note Book Author: Shahzaib Yaqoob<div>
 <div> Gmail :shahzaibmalik4488gmail.com<hdiv5> 
 
 ---
</div>


## NumPy Array Creation Functions

This section covers several NumPy functions for creating arrays:

- **`np.array()`**: Create an array from a Python list or iterable.

- **`np.zeros()`**: Create an array filled with zeros.

- **`np.ones()`**: Create an array filled with ones.

- **`np.empty()`**: Create an array without initializing its values.

- **`np.arange()`**: Create an array with regularly spaced values.

- **`np.linspace()`**: Create an array with evenly spaced values over a specified range.

- **`dtype`**: Attribute indicating the data type of the array elements.


In [10]:
import numpy as np

In [11]:
# np.array()
print("Array        :",np.array([1,2,3,4,5,6]))

# np.zeros()
print("np.zeros(6)  : ",np.zeros(6))

# np.ones()
print("np.ones(6)   : ",np.ones(6))

# np.empty()
print("np.empty()   : ",np.empty(2)) 

#np.arange()
print("np.arange()  : ", np.arange(5, 10))

# np.linespace()
print("np.linspace(): ",np.linspace(1,10,5))

# Create an array with specified data type (float64)
print("np.dtype()   : ",  np.array([1, 2, 3, 4, 5, 6], dtype=np.float64).dtype) 

Array        : [1 2 3 4 5 6]
np.zeros(6)  :  [0. 0. 0. 0. 0. 0.]
np.ones(6)   :  [1. 1. 1. 1. 1. 1.]
np.empty()   :  [ 4.27521809e+244 -2.64210566e-190]
np.arange()  :  [5 6 7 8 9]
np.linspace():  [ 1.    3.25  5.5   7.75 10.  ]
np.dtype()   :  float64


## Sorting ,Adding, and Removing

This section covers some useful NumPy functions for adding, removing, and sorting elements in arrays.

- **`np.sort()`**: Sort the elements of an array along a specified axis. You can customize the sorting behavior by specifying parameters such as the axis, kind, and order.

- **`np.concatenate()`**: Concatenation is like combining or joining multiple arrays together. It's like putting them side by side. The np.concatenate() function helps to do this in Python..


In [12]:
#np.sort()
array_to_sort = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
sorted_array = np.sort(array_to_sort)
print("Original Array:", array_to_sort)
print("----------------------------------------")
print("Sorted Array:", sorted_array)

Original Array: [3 1 4 1 5 9 2 6 5 3 5]
----------------------------------------
Sorted Array: [1 1 2 3 3 4 5 5 5 6 9]


In [13]:
#np.concatenated Array
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.concatenate((array1, array2))
print("Array 1 : ", array1)
print("Array 2 : ", array2)
print("----------------------------------------")
print("Concatenated Array : ", concatenated_array)

Array 1 :  [1 2 3]
Array 2 :  [4 5 6]
----------------------------------------
Concatenated Array :  [1 2 3 4 5 6]


## Understanding Array Attributes

In this section, we will discuss important characteristics of NumPy arrays that give us details about their dimensions and size.
- **`ndarray.shape`**: The ndarray.shape attribute returns a tuple with the array's dimensions.

- **`ndarray.ndim`**: Returns the number of dimensions (axes) of the array.

- **`ndarray.size`**: Returns the total number of elements in the array.


### `ndarray.ndim`

`ndarray.ndim` This attribute provides important details about the array's structure.

In [23]:
# ndarray.shape()
Array=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print("Shape of Array: ",Array.shape)
# nd.size()
print("Size of Array: ",Array.size)

Shape of Array:  (2, 6)
Size of Array:  12


## Reshaping Arrays

You can change the dimensions of an array while keeping the same total number of elements by reshaping it.NumPy provides the `reshape()` function for this purpose.

### `np.reshape()`

The `np.reshape()` function is used to change the shape of an array without changing its data


In [30]:
# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to a 2x3 array
reshaped_array = original_array.reshape((3,2))

print("Original Array:")
print(original_array)
print("---------------------")
print("Reshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]
---------------------
Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


In [35]:
reshaped_array = np.reshape(original_array, newshape=(2, 3), order='C')

print("Original Array:")
print(original_array)

print("Reshaped Array:")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]
Reshaped Array:
[[1 2 3]
 [4 5 6]]


## Indexing and Slicing in NumPy
Indexing and slicing are important operations in NumPy that enable you to access and modify elements of arrays.

### `Indexing`

Indexing is the process of accessing specific elements within an array. In NumPy arrays, the indexing starts at zero, meaning the first element is accessed using an index of 0. To index into an array, square brackets [] are used.
### `Slicing` 
Involves extracting a portion (a subarray) of an array. The basic syntax is start:stop

In [42]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Access the second element (index 3)
print("Original 1D Array:", arr_1d)
print("Second Element:", arr_1d[2])

print("Array Slicing: ",arr_1d[:3])
print("Array Slicing: ",arr_1d[2:4])




Original 1D Array: [1 2 3 4 5]
Second Element: 3
Array Slicing:  [1 2 3]
Array Slicing:  [3 4]


In [50]:
filter_Array = np.array([[1 , 2, 3, 4]])
print("Filter Array : ",filter_Array[filter_Array<3])
filter_Array = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Filter Array : ",filter_Array[(filter_Array<11) & (filter_Array>=4)])



Filter Array :  [1 2]
Filter Array :  [ 4  5  6  7  8  9 10]
