---
<div style="text-align: center; font-family: 'Times New Roman', Times, serif;">
  <h1>Python</h1>
 <h1>Numpy</h1>
 <div> Note Book Author: Shahzaib Yaqoob<div>
 <div> Gmail :shahzaibmalik4488gmail.com<hdiv5> 
 
 ---
</div>


In [32]:
import numpy as np

Some NumPy functions  `np.vstack(), np.hstack(), np.hsplit(), and copy()`

`np.vstack():` The NumPy function `np.vstack()` is used to concatenate arrays along the vertical axis. The arrays must have the same number of columns.

`np.hstack():` Concatenates arrays horizontally (column-wise).

`np.hsplit():` This function divides an array at specific positions, splitting it horizontally.

`copy():` Creates a copy of an array.


In [33]:
# np.vstack()
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
result = np.vstack((arr2, arr1))
print(result)


[[5 6]
 [1 2]
 [3 4]]


In [34]:
# np.hstack()
arr1 = np.array([[1, 2],[6,7]])
arr2 = np.array([[3, 4],[8,9]])
result = np.hstack((arr1, arr2))
print(result)

[[1 2 3 4]
 [6 7 8 9]]


In [35]:
# np.hsplit()
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
# split into 2 parts
result = np.hsplit(array,2)
print(result)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [36]:
# np.copy()
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
copy = np.copy(array)
print(copy)

[[1 2 3 4]
 [5 6 7 8]]


# Basic Array Operations

In NumPy, arrays allow for a variety of mathematical operations. 

Here are some basic array operations:

- `Addition`
- `Subtraction`
- `Multiplication`
- `Division`


In [40]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
# Addition
result_add = array1 + array2
# Substraction
result_sub = array1 - array2
# Multiplaction
result_mull = array1 * array2
# Division
result_div = array1 / array2

print(": Addation : \n",result_add ,"\n")
print(": Substraction : \n",result_sub,"\n")
print(": Multiplaction : \n",result_mull,"\n")
print(": Division : \n",result_div,"\n")

: Addation : 
 [[ 8 10 12]
 [14 16 18]] 

: Substraction : 
 [[-6 -6 -6]
 [-6 -6 -6]] 

: Multiplaction : 
 [[ 7 16 27]
 [40 55 72]] 

: Division : 
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]] 



## Some additional aggregation functions
- `Mean: ` The mean is the sum of all values in a dataset divided by the number of values, representing the average.
- `Median: ` The median is the middle value of a dataset when it is ordered. 
- `Mode: ` The "most common" or "most popular" value in the dataset.
- `Min: ` It represents the lowest numerical value in the dataset.
- `Max: ` It represents the greatest numerical value in the dataset.
- `Unique: `Function that returns the unique elements of an array,
- `flip: `         Reverse an array

In [67]:
from scipy import stats

In [75]:
array1 = np.array([1, 2, 3,4,5,6,7,8])
print("Mean of Array   :",array1.mean())
print("Medium of Array :",np.median(array1))
print("Mode of Array   :", stats.mode(array1)[0])
print("Min of Array    :", array1.min())
print("Max of Array    :", array1.max())
print("Unique of Array :", np.unique(array1))


Mean of Array   : 4.5
Medium of Array : 4.5
Mode of Array   : 1
Min of Array    : 1
Max of Array    : 8
Unique of Array : [1 2 3 4 5 6 7 8]
